apiVersion: v1
kind: ConfigMap
metadata:
  name: pmm-be-config
  namespace: pmm-app
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"