apiVersion: v1
kind: Secret
metadata:
  name: pmm-db-secret
  namespace: pmm-app
type: Opaque
data:
  # Values are base64 encoded
  # POSTGRES_DB: pmm -> cG1t
  # POSTGRES_USER: pmm_user -> cG1tX3VzZXI=
  # POSTGRES_PASSWORD: pmm_pass -> cG1tX3Bhc3M=
  POSTGRES_DB: cG1t
  POSTGRES_USER: cG1tX3VzZXI=
  POSTGRES_PASSWORD: cG1tX3Bhc3M=