name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE cluster connection
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: pmm-cluster    
          location: asia-south1 
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          echo "Deploying to GKE..."
          kubectl apply -f k8s/